### ISSUE TITLE
Error 405 on Strapi request

### ISSUE THREAD

**Issue by dulcetti** [kristinacowan/wordpress-2-strapi#4]
I've tried, but it's returning an error =/:

`UnhandledPromiseRejectionWarning: Error: Request failed with status code 405`

The response:
```
response: {
  status: 405,
  statusText: 'Method Not Allowed',
  headers: {
    vary: 'Origin',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    'x-frame-options': 'SAMEORIGIN',
    allow: 'HEAD, GET',
    'x-powered-by': 'Strapi <strapi.io>',
    'x-response-time': '17ms',
    'content-type': 'text/plain; charset=utf-8',
    'content-length': '18',
    date: 'Mon, 17 May 2021 20:10:04 GMT',
    connection: 'close'
  },
  config: {
    url: 'http://localhost:1337/admin/auth/local',
    method: 'post',
    data: '{"identifier":"MYEMAIL","password":"MYPASSWORD"}',
    headers: [Object],
    transformRequest: [Array],
    transformResponse: [Array],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
}
```

**Comment by samrit** [comment]
Strapi's endpoints have changes since. You will need to change `strapiUrl + "/admin/auth/local"`  to `strapiUrl + "/auth/local"`

**Comment by kumard3** [comment]
I am getting this error while exporting to JSON file.

Parsing wordpress export file
/home/kumar/code/github/wordpress-2-strapi/wp-export-to-json.js:119
const authors = (_get(otherProps, "wp:author") || []).map((a) => {
                                                      ^

TypeError: (_get(...) || []).map is not a function
    at Object.<anonymous> (/home/kumar/code/github/wordpress-2-strapi/wp-export-to-json.js:119:55)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
